import { EnrichedItem } from './inventory.types';

export const MOCK_INVENTORY: EnrichedItem[] = [
  {
    listingId: null,
    marketHashName: 'AK-47 | Redline (Field-Tested)',
    imageUrl: 'https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I4oYwVb6qmZMxBiU5MzBnVs7c5YRiZwxBjJlTLvbSvMC2wABDoF17HfOdkbKhIANr1eb3YiE2m5nhMu-a3r6glWZXu59ggeuIrNmj3FW2qEd8-zQ_Y-jDChhSbFRL/',
    currentPrice: 12.50,
    predictedPrice: 10.20,
    undervaluePct: -0.18,
    totalSupply: 42301,
    weaponType: 'Rifle',
    weapon: 'AK-47',
    collection: 'The Phoenix Collection',
    rarity: 'Classified',
    wear: 'Field-Tested',
    isStatTrak: false,
    isSouvenir: false,
    float: 0.231,
    paintSeed: 321,
  },
  {
    listingId: null,
    marketHashName: 'AWP | Asiimov (Battle-Scarred)',
    imageUrl: 'https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I4oYwVb6qmZMxBiU5MzBnVs7c5YRiZwxBjJlTLvbSvMC2wABDoF17HfOdkbKhIANr1eb3YiE2m5nhMu-a3r6glWZXu59ggeuIrNmj3FW2qEd8-zQ_Y-jDChhSbFRL/',
    currentPrice: 45.00,
    predictedPrice: 52.30,
    undervaluePct: 0.162,
    totalSupply: 18420,
    weaponType: 'Sniper Rifle',
    weapon: 'AWP',
    collection: 'The Breakout Collection',
    rarity: 'Covert',
    wear: 'Battle-Scarred',
    isStatTrak: false,
    isSouvenir: false,
    float: 0.812,
    paintSeed: 569,
  },
  {
    listingId: null,
    marketHashName: 'StatTrak™ Glock-18 | Fade (Factory New)',
    imageUrl: 'https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I4oYwVb6qmZMxBiU5MzBnVs7c5YRiZwxBjJlTLvbSvMC2wABDoF17HfOdkbKhIANr1eb3YiE2m5nhMu-a3r6glWZXu59ggeuIrNmj3FW2qEd8-zQ_Y-jDChhSbFRL/',
    currentPrice: 320.00,
    predictedPrice: 295.00,
    undervaluePct: -0.078,
    totalSupply: 3201,
    weaponType: 'Pistol',
    weapon: 'Glock-18',
    collection: 'The Cache Collection',
    rarity: 'Restricted',
    wear: 'Factory New',
    isStatTrak: true,
    isSouvenir: false,
    float: 0.014,
    paintSeed: 42,
  },
];
